<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><Version>1.0.1</Version></PropertyGroup>
<ItemGroup><PackageReference Include="Jellyfin.Controller" Version="12.1.0" PrivateAssets="all"/><FrameworkReference Include="Microsoft.AspNetCore.App"/><EmbeddedResource Include="config.html"/></ItemGroup>
</Project>
